# Generated by Django 4.2.1 on 2023-05-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t2idb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text2image',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
